apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
  labels:
    app: test
  annotations:
    kubevs/virtualIPs: popp-test-qa.po.server.lan
    kubevs/service.https.persistent: 'true'
    kubevs/service.https.scheduler: lc
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
  selector:
    app: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &LABELS
    app: &APP test
  name: *APP
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: *APP
  template:
    metadata:
      labels: *LABELS
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: test
        readinessProbe:
          periodSeconds: 1
          tcpSocket:
            port: 80
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
        image: nginx

